# netlify.toml — minimum viable scaffold
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"     # faster cold starts
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/api/:splat"
  status = 200
  force  = true               # optional but recommended
